### ISSUE TITLE
Could not find artifact org.primefaces.themes:bootstrap:jar:1.0.10 in central

### ISSUE THREAD

**Issue by artyom-88** [igormukhin/primefaces-spring-sample#2]
Command mvn spring-boot:run doesn't work:
Could not resolve dependencies for project de.igormukhin.samples:spring-boot-org.acme.sample-jsf:war:0.0.1-SNAPSHOT: Could not find artifact org.primefaces.themes:bootstrap:jar:1.0.10 in central (https://repo.maven.apache.org/maven2)

![image](https://user-images.githubusercontent.com/13161268/57981120-1cb8a480-7a3c-11e9-8e00-58a09a23db31.png)

**Comment by artyom-88** [comment]
You should add to pom.xml:
    <repositories>
        <repository>
            <id>prime-repo</id>
            <name>PrimeFaces Maven Repository</name>
            <url>http://repository.primefaces.org</url>
            <layout>default</layout>
        </repository>
    </repositories>

**Comment by igormukhin** [comment]
First line in README.me:

> ATTENTION: I do not recommend this example anymore! Better use JoinFaces
